### ISSUE TITLE
missing file `./out/Commandline/Commandline_history_filtered_flat.json` mentioned in README

### ISSUE THREAD

**Issue by itaowei** [PPPI/Flexeme#2]
Thanks for your great work!

When I carefully read the [README file](https://github.com/PPPI/Flexeme#corpus), I find the file `./out/Commandline/Commandline_history_filtered_flat.json` is missing. Is this file renamed? 
I want to survey your dataset but I feel difficult to understand the corpus. 
Could you please help me by providing one example of the tangled commit constructed by your method including its related source commit URLs?

Looking forward to your reply!
Thanks in advance!

**Comment by PPPI** [comment]
Hey, thank you for your interest in the project. I just double checked and I do not think I provided the corpora in the repository, only a way to generate them. 

The data is linked from the README to an external data store due to size. It is located [here](https://liveuclac-my.sharepoint.com/:f:/g/personal/ucabpp1_ucl_ac_uk/EkNrHsAyWPZCkhOsXXvERmIBpiraNlREcEEO4keHUFdRhA?e=6vxyCs) and requires the password `Flexeme_data_2020`. Hope you can access it from here, if not, happy to guide you in recreating the data as per the README.

As for the corpus format, I will admit it is not ideal, so here is the brief of how it is structured:
`./out/Commandline/Commandline_history.json` (that `_filtered_flat` is what you get by default, inspecting the corpus I have locally, it seems renamed) contains chains of commits squashed together: 
```json
[
  ["46bf0bc0b6ab9b9a41cc5c1c1cc41595910a465b", "dd0760557692f3fd6b7920192fd4b0b0df85c673"],
  ["27cd31cef64157bfa1a1eb7a8cec58d171ebbeb1", "efdf9da0edec6b74253d59300fa214e54144e431", "add33a5b96c0215cbc6de7e7abc34cc44a99a1af"], 
  ["94e4f35211186aa7bc1decf201dd8e402033ac73", "7aa501d534a657c388f94f66127b4f8dde64ac59"],
  ["5d6d5be252b2b199d76d8ced21667767e2002fb5", "142da4f95c1457cafce8547e1cfe990067f2e097", "26dac3b516bf5e7d1d8e6c906b3f948222459e0c"],
...
]
```
for example: ["46bf0bc0b6ab9b9a41cc5c1c1cc41595910a465b", "dd0760557692f3fd6b7920192fd4b0b0df85c673"]
will be found under `./data/Commandline/46bf0bc0b6ab9b9a41cc5c1c1cc41595910a465b_dd0760557692f3fd6b7920192fd4b0b0df85c673/<number of commits successfully squashed, so 1, 2, or 3>/merged.dot`
And this means that on the parent of 46bf0bc0b6ab9b9a41cc5c1c1cc41595910a465b we tried to put both of these commits.

The merged.dot graph itself represents the diff (node color indicated the operation).

As we did not keep diffs, you would either have to recreate them from the graph (line data is kept as we use it in the merger), or you would have to slightly change our corpus generation to output the diffs. We also slice the graph from changed nodes up to method boundaries to reduce corpus/graph sizes.

For an example, I include the 2 concerns graph from `0ac3cc8c7bbe0b8462b64e140f12d05328f1b2a5_c3279f2ff609f648446b021b4578a2570fe03c78`
[0ac3cc8c7bbe0b8462b64e140f12d05328f1b2a5_c3279f2ff609f648446b021b4578a2570fe03c78.pdf](https://github.com/PPPI/Flexeme/files/9136875/0ac3cc8c7bbe0b8462b64e140f12d05328f1b2a5_c3279f2ff609f648446b021b4578a2570fe03c78.pdf)

https://github.com/commandlineparser/commandline/commit/3a67a730f2edc383a759391bf4ccc5e5174d8176
https://github.com/commandlineparser/commandline/commit/0ac3cc8c7bbe0b8462b64e140f12d05328f1b2a5
https://github.com/commandlineparser/commandline/commit/c3279f2ff609f648446b021b4578a2570fe03c78

Are the commits involved. Note, the last two are not contiguous since we require the two _same author_ commits that occur one after the other ignoring the in-between commits.

Not sure if ideal, but hopefully gives you a feel for the data.

**Comment by itaowei** [comment]
Thank you so much for your detailed answer!
The example (`0ac3cc8c7bbe0b8462b64e140f12d05328f1b2a5_c3279f2ff609f648446b021b4578a2570fe03c78`) you gave helped me understand part of it, but I still have some questions on the merge.dot graph such as [0ac3cc8c7bbe0b8462b64e140f12d05328f1b2a5_c3279f2ff609f648446b021b4578a2570fe03c78.pdf](https://github.com/PPPI/Flexeme/files/9136875/0ac3cc8c7bbe0b8462b64e140f12d05328f1b2a5_c3279f2ff609f648446b021b4578a2570fe03c78.pdf).

This [pdf file](https://github.com/PPPI/Flexeme/files/9136875/0ac3cc8c7bbe0b8462b64e140f12d05328f1b2a5_c3279f2ff609f648446b021b4578a2570fe03c78.pdf) can be generated from the corpus (which is stored in .../corpora_clean/Commandline/0ac3cc8c7bbe0b8462b64e140f12d05328f1b2a5_c3279f2ff609f648446b021b4578a2570fe03c78/2/merge.dot).

The commit history (SHA, commit time, names of changed files in each commit) between `0ac3cc8c7bbe0b8462b64e140f12d05328f1b2a5` and `c3279f2ff609f648446b021b4578a2570fe03c78` in that repository is shown below. 

![0ac3cc8c7bbe0b8462b64e140f12d05328f1b2a5_c3279f2ff609f648446b021b4578a2570fe03c78](https://user-images.githubusercontent.com/19475586/184862538-6495f6e2-efad-4b26-a1c9-b44999b56554.png)

As the `merge.dot` graph represents diffs, the [pdf file](https://github.com/PPPI/Flexeme/files/9136875/0ac3cc8c7bbe0b8462b64e140f12d05328f1b2a5_c3279f2ff609f648446b021b4578a2570fe03c78.pdf) represents squashed diffs.
I tried to find the relation between the graph shown in [pdf file](https://github.com/PPPI/Flexeme/files/9136875/0ac3cc8c7bbe0b8462b64e140f12d05328f1b2a5_c3279f2ff609f648446b021b4578a2570fe03c78.pdf) and the commit history between `0ac3cc8c7bbe0b8462b64e140f12d05328f1b2a5` and `c3279f2ff609f648446b021b4578a2570fe03c78` but I failed. Could you help me to understand that graph furthermore?
I will describe my understanding first, please help to see if there is any problem.
During the commit history between `0ac3cc8c7bbe0b8462b64e140f12d05328f1b2a5` and `c3279f2ff609f648446b021b4578a2570fe03c78`, two `.cs` files were changed more than once: `src/CommandLine/Infrastructure/ResultExtensions.cs` and `src/CommandLine/Core/InstanceBuilder.cs`. Does it mean that the number of commits successfully squashed is no more than the number of changed `.cs` files (TWO) (is the same as the number of changed `.cs` files if not changed back)?

How the merge.dot (such as [pdf file](https://github.com/PPPI/Flexeme/files/9136875/0ac3cc8c7bbe0b8462b64e140f12d05328f1b2a5_c3279f2ff609f648446b021b4578a2570fe03c78.pdf)) is generated and which diffs are squashed and represented in this graph? For example, what file modifications are included in this [pdf file](https://github.com/PPPI/Flexeme/files/9136875/0ac3cc8c7bbe0b8462b64e140f12d05328f1b2a5_c3279f2ff609f648446b021b4578a2570fe03c78.pdf), `src/CommandLine/Infrastructure/ResultExtensions.cs` or `src/CommandLine/Core/InstanceBuilder.cs`?

(BTW, It seems that the [pdf file](https://github.com/PPPI/Flexeme/files/9136875/0ac3cc8c7bbe0b8462b64e140f12d05328f1b2a5_c3279f2ff609f648446b021b4578a2570fe03c78.pdf) is related to [src/CommandLine/Core/ValueMapper.cs](https://github.com/commandlineparser/commandline/blob/0ac3cc8c7bbe0b8462b64e140f12d05328f1b2a5/src/CommandLine/Core/ValueMapper.cs) but this file was changed only once between `0ac3cc8c7bbe0b8462b64e140f12d05328f1b2a5` and `c3279f2ff609f648446b021b4578a2570fe03c78`)

Looking forward to your kindly reply!
Thanks a lot in advance!

**Comment by PPPI** [comment]
> During the commit history between 0ac3cc8c7bbe0b8462b64e140f12d05328f1b2a5 and c3279f2ff609f648446b021b4578a2570fe03c78, two .cs files were changed more than once: src/CommandLine/Infrastructure/ResultExtensions.cs and src/CommandLine/Core/InstanceBuilder.cs. Does it mean that the number of commits successfully squashed is no more than the number of changed .cs files (TWO) (is the same as the number of changed .cs files if not changed back)?

The number of commits successfully squashed will not depend on the number of files, rather on the number of surviving/non-overlapping hunks from the edits of each commit.

- Example 1: a chain of 3 commits, all edit independent files, by squashing we should have all edits in a single commit with clusters from 3 original commits, the surviving number should be 3.

- Example 2: the same files are edited multiple times, 3 commit chain. The edits don't overlap. The surviving number should be 3

- Example 3: the same files are edited multiple times, 3 commit chain, one edit overrides a previous edit. The surviving number should be 2.

Also, please be aware that you have to restrict history to the same author to see what we consider as contiguous. There may be multiple commits we ignore between those we consider since we tried to mimic a _single_ developer forgetting to commit their workspace.

Now to explain the graph a bit: 
 - When generating it from scratch, you will notice that we generate a δPDG/δNFG per source file. 
 - We then merge them into a single graph, add missing call edges as appropriate and start a slicing process to reduce the graph size and make analysis tractable. 

The slice works as follows: 
  - From each edited node, perform a forward and backward slice along control, name, and data edges until you reach method boundaries. 
  - Preserve call edges if both the source and the target remain in the slice. 

This might explain why the graphs look a bit odd/harder to relate to a particular file. They contain nodes from potentially multiple and do not contain all nodes.

I kept the details a bit high level, but am happy to explain more and/or point to the source code. Sadly, the Roslyn code (C#) for PDG extraction is lost so I can only provide the binary, but it is fairly standard and just an implementation similar to tinyPDG but for C#. 

Hope this helps.
-Profir
