### ISSUE TITLE
Extracting PDG in Java

### ISSUE THREAD

**Issue by k1rep** [PPPI/Flexeme#5]
Hi, firstly thank you for your work.
I have a Java project right now and I want to use your tool to extract a multi-version program dependency graph, and since the provided PDGExtractor is oriented towards C#, I would like to use TinyPDG( https://github.com/YoshikiHigo/TinyPDG ) to extract the PDG, followed by Flexeme for subsequent processing. However, I have encountered some problems, TinyPDG may not produce graph information like **span**, could you please give me some guidance on what I need to change roughly on TinyPDG to adapt to Flexeme.
The output of TinyPDG looks like this:
`digraph {
subgraph cluster0 {
label = "method <5...10>";
0.3 [style = filled, label = "return c; <9>", fillcolor = deeppink, shape = ellipse];
0.1 [style = filled, label = "int b = 20; <7>", fillcolor = white, shape = ellipse];
0.0 [style = filled, label = "int a = 10; <6>", fillcolor = white, shape = ellipse];
0.2 [style = filled, label = "int c = a + b; <8>", fillcolor = white, shape = ellipse];
0.4 [style = filled, label = "Enter <5...10>", fillcolor = aquamarine, shape = diamond];
0.0 -> 0.1 [style = bold, label=""];
0.0 -> 0.2 [style = solid, label="a"];
0.1 -> 0.2 [style = solid, label="b"];
0.1 -> 0.2 [style = bold, label=""];
0.2 -> 0.3 [style = solid, label="c"];
0.2 -> 0.3 [style = bold, label=""];
0.4 -> 0.0 [style = dotted, label="true"];
0.4 -> 0.0 [style = bold, label=""];
0.4 -> 0.1 [style = dotted, label="true"];
0.4 -> 0.2 [style = dotted, label="true"];
0.4 -> 0.3 [style = dotted, label="true"];
}
}`
and when I plugged into Flexeme:
`{'attributes': {}, 'name': 'PDG', 'type': 'digraph', 'strict': False, 'suppress_disconnected': False, 'simplify': False, 'current_child_sequence': 87, 'nodes': {}, 'edges': {}, 'subgraphs':cluster0,cluster1,...}`there's no nodes and edges, which only present in the subgraphs.

**Comment by PPPI** [comment]
Hello,

Having re-read my code, Flexeme does assume the span attribute to perform some fuzzy anchoring as a starting point for the merging procedure. Specifically matching from diff to nodes. I do not have a nice answer here, sadly. 

Just at a glance, I can see that the dot file format differs and, since Flexeme assumes meaning from the dot file colours, these should be matched across and changed to match the assumptions from Flexeme. However, this should be a simple find-and-replace post-processing.

For the file/span node metadata, I am not sure which path is easier, post-processing or changing TinyPDG; if TinyPDG has access to the line number as it creates the graph, I would suspect the best bet would be to find where it creates nodes and to alter that to include the start and end line numbers of the node in question.

I am not particularly familiar with Java, but a quick search through the TinyPDG source landed me at this: https://github.com/YoshikiHigo/TinyPDG/blob/e1575b30f3a89ff6877eeab5b9786e507cc5573f/src/main/java/yoshikihigo/tinypdg/pe/ProgramElementInfo.java#L14
```java
	final public int startLine;
	final public int endLine;
```
The span output you want is `f"{startLine}-{endLine}"` so my suggestion would be to find where the dot file emits this, see if the object is a ProgramElement or descendent of this and if you have access to these fields to output as an additional field in the dotfile.

I hope this pointer helps.
